version: '3'

services: 
  app: 
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
     - '80:4000'
    links:
     - mongo
     - oracle-xe
  mongo:
    container_name: mongo
    image: mongo
    ports: 
     - '27017:27017'
  oracle-xe:
    container_name: oracle_xe
    image: hackleman/oracleproject
    ports:
      - '32118:1521'
      - '35518:5500'
    environment:
      - ORACLE_PWD=Oracle18
    volumes:
      - /data:/opt/oracle/oradata